services:
  db:
    image: mysql:8.3
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: money_password
      MYSQL_DATABASE: money_db
    ports:
      - 3306:3306
    volumes:
      - db:/var/lib/mysql

  backend:
    image: money-backend
    build: .
    depends_on:
      - db
    ports:
      - 8000:8000
    env_file:
      - dev.env

volumes:
  db:
